export const projects = [
    {
        name: "Tagabaybay",
        link: "https://github.com/Mango-Cats/tagabaybay",
        description: "",
        tags: [],
    },
    {
        name: "Tortilla",
        link: "https://github.com/chua-e/tortilla",
        description: "",
        tags: [],
    },
    {
        name: "Tagabaybay",
        link: "https://github.com/Mango-Cats/tagabaybay",
        description: "",
        tags: [],
    },
    {
        name: "Tagabaybay",
        link: "https://github.com/Mango-Cats/tagabaybay",
        description: "",
        tags: [],
    },
    {
        name: "Tagabaybay",
        link: "https://github.com/Mango-Cats/tagabaybay",
        description: "",
        tags: [],
    },
    {
        name: "Tagabaybay",
        link: "https://github.com/Mango-Cats/tagabaybay",
        description: "",
        tags: [],
    },
    {
        name: "Tagabaybay",
        link: "https://github.com/Mango-Cats/tagabaybay",
        description: "",
        tags: [],
    },
    {
        name: "Tagabaybay",
        link: "https://github.com/Mango-Cats/tagabaybay",
        description: "",
        tags: [],
    },
    {
        name: "Tagabaybay",
        link: "https://github.com/Mango-Cats/tagabaybay",
        description: "",
        tags: [],
    },
    {
        name: "Tagabaybay",
        link: "https://github.com/Mango-Cats/tagabaybay",
        description: "",
        tags: [],
    },
    {
        name: "Tagabaybay",
        link: "https://github.com/Mango-Cats/tagabaybay",
        description: "",
        tags: [],
    },
    {
        name: "Tagabaybay",
        link: "https://github.com/Mango-Cats/tagabaybay",
        description: "",
        tags: [],
    },
    {
        name: "Tagabaybay",
        link: "https://github.com/Mango-Cats/tagabaybay",
        description: "",
        tags: [],
    },
    {
        name: "Tagabaybay",
        link: "https://github.com/Mango-Cats/tagabaybay",
        description: "",
        tags: [],
    },
    {
        name: "Tagabaybay",
        link: "https://github.com/Mango-Cats/tagabaybay",
        description: "",
        tags: [],
    },
    {
        name: "Tagabaybay",
        link: "https://github.com/Mango-Cats/tagabaybay",
        description: "",
        tags: [],
    },
    {
        name: "Tagabaybay",
        link: "https://github.com/Mango-Cats/tagabaybay",
        description: "",
        tags: [],
    },
    {
        name: "Tagabaybay",
        link: "https://github.com/Mango-Cats/tagabaybay",
        description: "",
        tags: [],
    },
    {
        name: "Tagabaybay",
        link: "https://github.com/Mango-Cats/tagabaybay",
        description: "",
        tags: [],
    },
    {
        name: "Tagabaybay",
        link: "https://github.com/Mango-Cats/tagabaybay",
        description: "",
        tags: [],
    },
];
